version: "3.9"
services:
  recipe-database:
    image: mongo
    ports:
      - "27017:27017"
  recipe-backend:
    build: backend/
    environment:
      - PORT=3001
      - DATABASE_URL=mongodb://recipe-database:27017/recipes
      - JWT_SECRET=dev-secret
    ports:
      - "3001:3001"
    depends_on:
      - recipe-database
  recipe-frontend:
    build:
      context: .
      args:
        VITE_BACKEND_URL: http://localhost:3001/api/v1
    ports:
      - "3000:80"
    depends_on:
      - recipe-backend
